[ADD][11.0] Adding module project_agile_workflow_transitions_by_task_type
OCA/project-agile pull request #8
Opened 2018-02-23 21:23 UTC by pnajman-modoolar

Hello,

Module ``project_agile_workflow_transitions_by_task_type`` module extends [project_agile](https://github.com/OCA/project-agile/pull/4) and introduces configuration of allowed task types for a specific task workflow transition.

Kind Regards,
Petar

2018-02-24 01:28 UTC, elicoidal requested changes
Can you add Unit tests and simple demo data?

2018-02-24 01:28 UTC, elicoidal commented on project_agile_workflow_transitions_by_task_type/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
Many remarks from here https://github.com/OCA/web/pull/881#pullrequestreview-99094143 applies in this PR (and probably most of the PR done today :smile: )

2018-02-24 01:28 UTC, elicoidal commented on project_agile_workflow_transitions_by_task_type/models/project_workflow.py
> +            x
I prefer to have meaningful names even for this kind of variable

2018-06-07 09:26 UTC, pnajman-modoolar commented on project_agile_workflow_transitions_by_task_type/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
Fixed :)

2018-10-31 13:44 UTC, closed without merging