[ADD][11.0] Adding module project_agile_jira
OCA/project-agile pull request #9
Opened 2018-02-23 21:29 UTC by pnajman-modoolar

Hello,

Module ``project_agile_jira`` extend [project_agile](https://github.com/OCA/project-agile/pull/4) and enables us to migrate projects and tasks from JIRA to Odoo. This is very raw module and it's only usage is for migration purpose and not to be used as a JIRA synchronizer, for that there are other modules.

Unfortunately, JIRA does not have fully covered API route to read workflow with all states and transitions,  as far as I know at this moment, and thus it's not full automated. In order for the module to be able to map JIRA task states with task stages, one should create workflow in Odoo with the same stage names as in JIRA, so the module could map them properly.

Kind Regards,
Petar

2018-02-24 12:21 UTC, elicoidal requested changes
thanks for the module. some format details and no functional test.
Would miss UT and DD

2018-02-24 12:21 UTC, elicoidal commented on project_agile_jira/models/jira_worker.py
> +                _logger.info("Failed to write to database!: %s", str(ex))
remove "!"

2018-02-24 12:21 UTC, elicoidal commented on project_agile_jira/views/jira_config_views.xml
> +                        <button class="oe_stat_button" type="object" name="synchronize_projects" icon="fa-download" string="Synchronize Projects"/>
Can you format a bit the xml for readability?

2018-02-24 12:21 UTC, elicoidal commented on project_agile_jira/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
Please see: https://github.com/OCA/web/pull/881#pullrequestreview-99094143

2018-06-07 09:24 UTC, pnajman-modoolar commented on project_agile_jira/models/jira_worker.py
> +                _logger.info("Failed to write to database!: %s", str(ex))
Fixed

2018-06-07 09:24 UTC, pnajman-modoolar commented on project_agile_jira/views/jira_config_views.xml
> +                        <button class="oe_stat_button" type="object" name="synchronize_projects" icon="fa-download" string="Synchronize Projects"/>
Fixed. I hope it's ok now ...

2018-10-31 13:44 UTC, closed without merging